---
- name: Install git
  become: yes
  yum:
    state: present
    name: "{{ item }}"
  with_items:
    - git

- name: Check if devstack cloned
  stat:
    path: "/home/{{ ansible_user }}/devstack"
  register: devstack_st

- name: Clone devstack
  shell: git clone https://github.com/openstack-dev/devstack
  args:
    chdir: "/home/{{ ansible_user }}"
  when: not devstack_st.stat.exists

- name: Checkout branch
  shell: "git checkout {{ os_branch }}"
  args:
    chdir: "/home/{{ ansible_user }}/devstack"

- name: Copy local.conf
  template:
    src: templates/local.conf
    dest: "/home/{{ ansible_user }}/devstack/local.conf"

- name: Upload patches
  template:
    src: "templates/{{ item }}"
    dest: "/home/{{ ansible_user }}/{{ item }}"
    mode: a+x
  with_items:
    - 01-mitaka-requirements.sh

- name: Execute patches
  shell: "bash -x /home/{{ ansible_user }}/{{ item }}"
  with_items:
    - 01-mitaka-requirements.sh
  when: os_branch == "stable/mitaka"

- name: Run stack.sh
  shell: ./stack.sh > /tmp/devstack.log
  args:
    chdir: "/home/{{ ansible_user }}/devstack"

- name: Open port 80 & 6080 for horizon
  become: yes
  iptables:
    chain: INPUT
    action: insert
    protocol: tcp
    jump: ACCEPT
    destination_port: "{{ item }}"
  with_items:
    - 80
    - 6080
