# -*- mode: ruby -*-
# vi: set ft=ruby :

require "vagrant-vsphere"
require 'yaml'

configs = YAML.load_file("#{Dir.home}/.vagrant.d/vsphere.yaml")

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.ssh.username = configs['ssh']['user']
  config.ssh.password = configs['ssh']['password']
  config.ssh.keys_only = false

  config.vm.provider :vsphere do |vsphere|
    vsphere.host = configs['vsphere']['vcenter']
    vsphere.user = configs['vsphere']['user']
    vsphere.password = configs['vsphere']['password']
    vsphere.insecure = true
    vsphere.data_center_name = "Datacenter"
    vsphere.compute_resource_name = 'Cluster1'
    # vsphere.resource_pool_name = 'vagrant'
    vsphere.data_store_name = 'datastore1'

    # vsphere.name = "kube-#{i}"
    vsphere.template_name = "Templates/CentOS7-Server"
    vsphere.vm_base_path = "vagrant-machines"
    # vsphere.clone_from_vm = true
    vsphere.linked_clone = true

    vsphere.ssh_cidr = '172.20.1.0/24'
  end


  # Boot ansible
  vm_name = 'devstack-mitaka-0'
  config.vm.define vm_name do |n|
    n.vm.hostname = vm_name
    n.vm.provider :vsphere do |vsphere|
      vsphere.name = vm_name
      vsphere.memory_mb = 12368
      vsphere.cpu_count = 6
      vsphere.networks = [
        {'network': 'DPortGroup_VPN'}
      ]
      vsphere.nested_hv = true
    end
    n.vm.provision :ansible do |ansible|
        ansible.verbose = true
        ansible.limit = "all"
        ansible.galaxy_roles_path = "../../../ansible/roles/"
        ansible.groups = {
          "devstack" => vm_name,
        }
        ansible.playbook = "site.yml"
    end
  end
end