---
- name: Check if already joined
  stat:
    path: /var/log/kubeadm.log
  register: kubeadm_log

- name: Join master
  shell: kubeadm join --token="{{ hostvars['kube-0']['kubeadm_token']['stdout'] }}" kube-0 | tee /var/log/kubeadm.log
  when: kubeadm_log.stat.exists == false
