---
- name: Pull images
  docker_image:
    name: "{{ item }}"
  with_items:
    - openoint/common-services-msb
    - openoint/common-services-extsys
    - openoint/common-services-drivermanager
    - openoint/gso-service-gateway
    - openoint/gso-service-manager
    - openoint/gso-gui-portal
    - openoint/multivim-driver-vio

- name: Start msb
  docker_container:
    name: i-msb
    ports:
      - "80:80"
    image: openoint/common-services-msb

- name: Start other service
  docker_container:
    name: "{{ item }}"
    image: "openoint/{{ item }}"
    env:
      MSB_ADDR: "172.17.0.2:80"
  with_items:
    - gso-service-gateway
    - common-services-extsys
    - common-services-drivermanager
    - gso-gui-portal
    - gso-service-manager
    - multivim-driver-vio

