---
- name: Common settings
  become: yes
  hosts: all
  roles:
    - centos-common
    - docker

- name: Install shadowsocks
  hosts: all
  become: yes
  vars_files:
    - global_vars.yml
  roles:
    - shadowsocks