---
# You can use this file to override _any_ variable throughout Kolla.
# Additional options can be found in the 'kolla/ansible/group_vars/all.yml' file.
# Default value of all the commented parameters are shown here, To override
# the default value uncomment the parameter and change its value.

###################
# Kolla options
###################
# Valid options are [ COPY_ONCE, COPY_ALWAYS ]
#config_strategy: "COPY_ALWAYS"

# Valid options are [ centos, oraclelinux, ubuntu ]
kolla_base_distro: "{{ kolla_base_distro }}"

# Valid options are [ binary, source ]
kolla_install_type: "{{ kolla_install_type }}"

# Valid option is Docker repository tag
openstack_release: "{{ openstack_release }}"

# Location of configuration overrides
#node_custom_config: "/etc/kolla/config"

# This should be a VIP, an unused IP on your network that will float between
# the hosts running keepalived for high-availability. When running an All-In-One
# without haproxy and keepalived, this should be the first IP on your
# 'network_interface' as set in the Networking section below.
kolla_internal_vip_address: "{{ kolla_internal_vip_address }}"

# This is the DNS name that maps to the kolla_internal_vip_address VIP. By
# default it is the same as kolla_internal_vip_address.
kolla_internal_fqdn: "{{ kolla_internal_fqdn }}"

# This should be a VIP, an unused IP on your network that will float between
# the hosts running keepalived for high-availability. It defaults to the
# kolla_internal_vip_address, allowing internal and external communication to
# share the same address.  Specify a kolla_external_vip_address to separate
# internal and external requests between two VIPs.
kolla_external_vip_address: "{{ kolla_external_vip_address }}"

# The Public address used to communicate with OpenStack as set in the public_url
# for the endpoints that will be created. This DNS name should map to
# kolla_external_vip_address.
kolla_external_fqdn: "{{ kolla_external_fqdn }}"

####################
# Docker options
####################
# Below is an example of a private repository with authentication. Note the
# Docker registry password can also be set in the passwords.yml file.

{% if docker_registry is defined %}
docker_registry: "{{ docker_registry }}"
{% endif %}
{% if docker_namespace is defined %}
docker_namespace: "{{ docker_namespace }}"
{% endif %}
{% if docker_registry_username is defined %}
docker_registry_username: "{{ docker_registry_username }}"
{% endif %}
{% if docker_registry_password is defined %}
docker_registry_password: "{{ docker_registry_password }}"
{% endif %}


###############################
# Neutron - Networking Options
###############################
# This interface is what all your api services will be bound to by default.
# Additionally, all vxlan/tunnel and storage network traffic will go over this
# interface by default. This interface must contain an IPv4 address.
# It is possible for hosts to have non-matching names of interfaces - these can
# be set in an inventory file per host or per group or stored separately, see
#     http://docs.ansible.com/ansible/intro_inventory.html
# Yet another way to workaround the naming problem is to create a bond for the
# interface on all hosts and give the bond name here. Similar strategy can be
# followed for other types of interfaces.
network_interface: "{{ network_interface }}"

# These can be adjusted for even more customization. The default is the same as
# the 'network_interface'. These interfaces must contain an IPv4 address.
kolla_external_vip_interface: "{{ kolla_external_vip_interface }}"
api_interface: "{{ api_interface }}"
storage_interface: "{{ storage_interface }}"
cluster_interface: "{{ cluster_interface }}"
tunnel_interface: "{{ tunnel_interface }}"

# This is the raw interface given to neutron as its external network port. Even
# though an IP address can exist on this interface, it will be unusable in most
# configurations. It is recommended this interface not be configured with any IP
# addresses for that reason.
{% if neutron_external_interface is defined %}
neutron_external_interface: "{{ neutron_external_interface }}"
{% endif %}

# Valid options are [ openvswitch, linuxbridge ]
neutron_plugin_agent: "{{ neutron_plugin_agent }}"


####################
# keepalived options
####################
# Arbitrary unique number from 0..255
#keepalived_virtual_router_id: "51"


####################
# TLS options
####################
# To provide encryption and authentication on the kolla_external_vip_interface,
# TLS can be enabled.  When TLS is enabled, certificates must be provided to
# allow clients to perform authentication.
#kolla_enable_tls_external: "no"
{% if node_config_directory is defined %}
#kolla_external_fqdn_cert: "{{ node_config_directory }}/certificates/haproxy.pem"
{% endif %}


####################
# OpenStack options
####################
# Use these options to set the various log levels across all OpenStack projects
# Valid options are [ True, False ]
#openstack_logging_debug: "False"

# Valid options are [ novnc, spice ]
#nova_console: "novnc"

# OpenStack services can be enabled or disabled with these options
enable_aodh: "{{ enable_aodh }}"
enable_barbican: "{{ enable_barbican }}"
enable_ceilometer: "{{ enable_ceilometer }}"
enable_central_logging: "{{ enable_central_logging }}"
enable_ceph: "{{ enable_ceph }}"
enable_ceph_rgw: "{{ enable_ceph_rgw }}"
enable_cinder: "{{ enable_cinder }}"
enable_cinder_backend_iscsi: "{{ enable_cinder_backend_iscsi }}"
enable_cinder_backend_lvm: "{{ enable_cinder_backend_lvm }}"
enable_cinder_backend_nfs: "{{ enable_cinder_backend_nfs }}"
enable_cloudkitty: "{{ enable_cloudkitty }}"
enable_congress: "{{ enable_congress }}"
enable_destroy_images: "{{ enable_destroy_images }}"
enable_etcd: "{{ enable_etcd }}"
enable_gnocchi: "{{ enable_gnocchi }}"
enable_grafana: "{{ enable_grafana }}"
enable_heat: "{{ enable_heat }}"
enable_horizon: "{{ enable_horizon }}"
enable_influxdb: "{{ enable_influxdb }}"
enable_ironic: "{{ enable_ironic }}"
enable_kuryr: "{{ enable_kuryr }}"
enable_magnum: "{{ enable_magnum }}"
enable_manila: "{{ enable_manila }}"
enable_manila_backend_generic: "{{ enable_manila_backend_generic }}"
enable_manila_backend_hnas: "{{ enable_manila_backend_hnas }}"
enable_mistral: "{{ enable_mistral }}"
enable_mongodb: "{{ enable_mongodb }}"
enable_murano: "{{ enable_murano }}"
enable_multipathd: "{{ enable_multipathd }}"
enable_neutron_dvr: "{{ enable_neutron_dvr }}"
enable_neutron_lbaas: "{{ enable_neutron_lbaas }}"
enable_neutron_fwaas: "{{ enable_neutron_fwaas }}"
enable_neutron_qos: "{{ enable_neutron_qos }}"
enable_neutron_agent_ha: "{{ enable_neutron_agent_ha }}"
enable_neutron_vpnaas: "{{ enable_neutron_vpnaas }}"
enable_octavia: "{{ enable_octavia }}"
enable_rally: "{{ enable_rally }}"
enable_sahara: "{{ enable_sahara }}"
enable_searchlight: "{{ enable_searchlight }}"
enable_senlin: "{{ enable_senlin }}"
enable_solum: "{{ enable_solum }}"
enable_swift: "{{ enable_swift }}"
enable_telegraf: "{{ enable_telegraf }}"
enable_tacker: "{{ enable_tacker }}"
enable_tempest: "{{ enable_tempest }}"
enable_watcher: "{{ enable_watcher }}"

###################
# Ceph options
###################
# Ceph can be setup with a caching to improve performance. To use the cache you
# must provide separate disks than those for the OSDs
ceph_enable_cache: "{{ ceph_enable_cache }}"
# Valid options are [ forward, none, writeback ]
ceph_cache_mode: "{{ ceph_cache_mode }}"

# A requirement for using the erasure-coded pools is you must setup a cache tier
# Valid options are [ erasure, replicated ]
#ceph_pool_type: "replicated"

# Integrate ceph rados object gateway with openstack keystone
#enable_ceph_rgw_keystone: "no"


##############################
# Keystone - Identity Options
##############################

# Valid options are [ uuid, fernet ]
keystone_token_provider: "{{ keystone_token_provider }}"

# Interval to rotate fernet keys by (in seconds). Must be an interval of
# 60(1 min), 120(2 min), 180(3 min), 240(4 min), 300(5 min), 360(6 min),
# 600(10 min), 720(12 min), 900(15 min), 1200(20 min), 1800(30 min),
# 3600(1 hour), 7200(2 hour), 10800(3 hour), 14400(4 hour), 21600(6 hour),
# 28800(8 hour), 43200(12 hour), 86400(1 day), 604800(1 week).
fernet_token_expiry: {{ fernet_token_expiry }}


#########################
# Glance - Image Options
#########################
# Configure image backend.
glance_backend_file: "{{ glance_backend_file }}"
glance_backend_ceph: "{{ glance_backend_ceph }}"

#######################
# Ceilometer options
#######################
# Valid options are [ mongodb, mysql, gnocchi ]
ceilometer_database_type: "{{ ceilometer_database_type }}"


#######################
# Gnocchi options
#######################
# Valid options are [ file, ceph ]
gnocchi_backend_storage: "{{ gnocchi_backend_storage }}"


#################################
# Cinder - Block Storage Options
#################################
# Enable / disable Cinder backends
cinder_backend_ceph: "{{ cinder_backend_ceph }}"
cinder_volume_group: "{{ cinder_volume_group }}"
cinder_backup_driver: "{{ cinder_backup_driver }}"
cinder_backup_share: "{{ cinder_backup_share }}"
cinder_backup_mount_options_nfs: "{{ cinder_backup_mount_options_nfs }}"

#########################
# Nova - Compute Options
#########################
nova_backend_ceph: "{{ nova_backend_ceph }}"


##############################
# Horizon - Dashboard Options
##############################
horizon_backend_database: "{{ horizon_backend_database }}"


#######################################
# Manila - Shared File Systems Options
#######################################
# HNAS backend configuration
#hnas_ip:
#hnas_user:
#hnas_password:
#hnas_evs_id:
#hnas_evs_ip:
#hnas_file_system_name:

##################################
# Swift - Object Storage Options
##################################
# Swift expects block devices to be available for storage. Two types of storage
# are supported: 1 - storage device with a special partition name and filesystem
# label, 2 - unpartitioned disk  with a filesystem. The label of this filesystem
# is used to detect the disk which Swift will be using.

# Swift support two mathcing modes, valid options are [ prefix, strict ]
#swift_devices_match_mode: "strict"

# This parameter defines matching pattern: if "strict" mode was selected,
# for swift_devices_match_mode then swift_device_name should specify the name of
# the special swift partition for example: "KOLLA_SWIFT_DATA", if "prefix" mode was
# selected then swift_devices_name should specify a pattern which would match to
# filesystems' labels prepared for swift.
#swift_devices_name: "KOLLA_SWIFT_DATA"


################################################
# Tempest - The OpenStack Integration Test Suite
################################################
# following value must be set when enable tempest
{% if tempest_image_id is defined %}
tempest_image_id: {{ tempest_image_id }}
{% endif %}
{% if tempest_flavor_ref_id is defined %}
tempest_flavor_ref_id: {{ tempest_flavor_ref_id }}
{% endif %}
{% if tempest_public_network_id is defined %}
tempest_public_network_id: {{ tempest_public_network_id }}
{% endif %}
{% if tempest_floating_network_name is defined %}
tempest_floating_network_name: {{ tempest_floating_network_name }}
{% endif %}
{% if tempest_image_alt_id is defined %}
tempest_image_alt_id: {{ tempest_image_alt_id }}
{% endif %}
{% if tempest_flavor_ref_alt_id is defined %}
tempest_flavor_ref_alt_id: {{ tempest_flavor_ref_alt_id }}
{% endif %}