# -*- mode: ruby -*-
# vi: set ft=ruby :

require "vagrant-vsphere"
require 'yaml'

configs = YAML.load_file("#{Dir.home}/.vagrant.d/vsphere.yaml")

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.ssh.username = configs['ssh']['user']
  config.ssh.password = configs['ssh']['password']
  config.ssh.keys_only = false

  config.vm.provider :vsphere do |vsphere|
    vsphere.host = configs['vsphere']['vcenter']
    vsphere.user = configs['vsphere']['user']
    vsphere.password = configs['vsphere']['password']
    vsphere.insecure = true
    vsphere.data_center_name = "Datacenter"
    vsphere.compute_resource_name = 'Cluster1'
    # vsphere.resource_pool_name = 'vagrant'
    vsphere.data_store_name = 'datastore1'

    # vsphere.name = "kube-#{i}"
    vsphere.template_name = "Templates/CentOS7-Server"
    vsphere.vm_base_path = "vagrant-machines"
    # vsphere.clone_from_vm = true
    vsphere.linked_clone = true

    # vsphere.memory_mb = 4096
    # vsphere.cpu_count = 4
    vsphere.vlan = 'DPortGroup_VPN'
    vsphere.real_nic_ip = true
  end

  # Boot controller
  CON = 2
  (0..CON).each do |i|
    config.vm.define "kolla-controller-#{i}" do |n|
      n.vm.hostname = "kolla-controller-#{i}"
      n.vm.provider :vsphere do |vsphere|
        vsphere.name = "kolla-controller-#{i}"
        vsphere.memory_mb = 6192
        vsphere.cpu_count = 4
      end
    end
  end

  # Boot compute
  COM = 0
  (0..COM).each do |i|
    config.vm.define "kolla-compute-#{i}" do |n|
      n.vm.hostname = "kolla-cpmpute-#{i}"
      n.vm.provider :vsphere do |vsphere|
        vsphere.name = "kolla-compute-#{i}"
        vsphere.memory_mb = 4096
        vsphere.cpu_count = 4
      end
    end
  end

  # Boot storage
  STO = 0
  (0..STO).each do |i|
    config.vm.define "kolla-storage-#{i}" do |n|
      n.vm.hostname = "kolla-storage-#{i}"
      n.vm.provider :vsphere do |vsphere|
        vsphere.name = "kolla-storage-#{i}"
        vsphere.memory_mb = 2048
        vsphere.cpu_count = 2
      end
    end
  end

  # Boot network
  NET = 0
  (0..NET).each do |i|
    config.vm.define "kolla-network-#{i}" do |n|
      n.vm.hostname = "kolla-network-#{i}"
      n.vm.provider :vsphere do |vsphere|
        vsphere.name = "kolla-network-#{i}"
        vsphere.memory_mb = 2048
        vsphere.cpu_count = 2
      end
    end
  end

  # Boot ansible
  config.vm.define "kolla-ansible" do |n|
    n.vm.hostname = "kolla-ansible"
    n.vm.provider :vsphere do |vsphere|
      vsphere.name = "kolla-ansible"
      vsphere.memory_mb = 2048
      vsphere.cpu_count = 2
    end
    n.vm.provision :ansible do |ansible|
        ansible.verbose = true
        ansible.limit = "all"
        ansible.galaxy_roles_path = "../../ansible/roles/"
        ansible.groups = {
        "controller" => (0..CON).map {|j| "kolla-controller-#{j}"},
        "compute" => (0..COM).map {|j| "kolla-compute-#{j}"},
        "storage" => (0..STO).map {|j| "kolla-storage-#{j}"},
        "network" => (0..NET).map {|j| "kolla-network-#{j}"}
        }
        ansible.playbook = "site.yml"
    end
  end
end