---
- name: Add docker repo
  copy:
    src: files/docker.repo
    dest: /etc/yum.repos.d/docker.repo

- name: Install docker and docker-py
  yum:
    state: present
    update_cache: true
    name: "{{ item }}"
  with_items:
    - docker-engine
    - python-docker-py

- name: enable mount shared
  copy:
    src: files/docker.service
    dest: /etc/systemd/system/docker.service

- name: enable docker
  systemd:
    enabled: true
    state: started
    daemon_reload: yes
    name: docker

- name: debug
  debug: var=ansible_user

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes