---
- name: Install kolla
  pip:
    name: kolla
    version: "{{ kolla_version }}"

- name: Install kolla-ansible
  pip:
    name: kolla-ansible
    version: "{{ kolla_ansible_version }}"

- name: Generate configuration file
  template:
    src: templates/kolla.conf.j2
    dest: /etc/kolla/kolla.conf

- name: Generate password file
  shell: kolla-genpwd