---
- name: Install ansible
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - ansible
    - python-pip
    - python-devel
    - git
    - gcc

- name: Install kolla-ansible
  pip:
    name: "{{ item }}"
  with_items:
    - kolla-ansible
    - tox
    - python-openstackclient
    - python-neutronclient
    - python-heatclient
    - python-senlinclient

- name: Clone kolla-ansible
  shell: "[ -d /opt/kolla-ansible ] || git clone https://github.com/openstack/kolla-ansible /opt/kolla-ansible"

- name: mkdir /etc/kolla/config/nova
  file:
    path: /etc/kolla/config/nova
    recurse: yes
    state: directory

- name: Copy globals.yml
  template:
    src: templates/kolla-globals.yml
    dest: /etc/kolla/globals.yml

- name: copy nova-compute.config
  template:
    src: templates/nova-compute.conf
    dest: /etc/kolla/config/nova/nova-compute.conf

- name: Generate passwords
  shell: cd /opt/kolla-ansible && /usr/bin/cp -f etc/kolla/passwords.yml /etc/kolla/ && kolla-genpwd

- name: Change admin password
  lineinfile:
    regexp: "^keystone_admin_password"
    dest: /etc/kolla/passwords.yml
    line: "keystone_admin_password: {{ keystone_admin_password }}"
  when: keystone_admin_password is defined

- name: Generate inventory
  template:
    src: templates/kolla-inventory
    dest: /etc/kolla/kolla-inventory

- name: bootstrap server
  shell: kolla-ansible -i /etc/kolla/kolla-inventory bootstrap-servers -v > /tmp/kolla-bootstrap.log

- name: prechecks
  shell: kolla-ansible -i /etc/kolla/kolla-inventory prechecks -v > /tmp/kolla-prechecks.log

- name: pull kolla images
  shell: kolla-ansible -i /etc/kolla/kolla-inventory pull -v > /tmp/kolla-pull.log

- name: deploy kolla openstack
  shell: kolla-ansible -i /etc/kolla/kolla-inventory deploy -v > /tmp/kolla-deploy.log

- name: post deploy openstack
  shell: kolla-ansible -i /etc/kolla/kolla-inventory post-deploy -v > /tmp/kolla-postdeploy.log

- name: Generate id_rsa
  shell: ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -b 2048 -N ""

- name: Init resource
  shell: source /etc/kolla/admin-openrc.sh && /opt/kolla-ansible/tools/init-runonce > /tmp/kolla-init.log

- name: Get admin password
  shell: cat /etc/kolla/passwords.yml |grep keystone_admin_password| cut -d' ' -f2
  register: admin_password

- name: openstack horizon ip
  debug:
    msg: "{{ kolla_internal_vip_address }}"

- name: admin password
  debug: var=admin_password.stdout