# Nova compute settings
nova_virt_type: "qemu"

# Common settings
kolla_internal_vip_address: "{{ ansible_default_ipv4.address.split('.')[0] }}.{{ ansible_default_ipv4.address.split('.')[1] }}.{{ (ansible_default_ipv4.address.split('.')[2]|int)+1 }}.{{ ansible_default_ipv4.address.split('.')[3] }}"
kolla_internal_fqdn: "{{ kolla_internal_vip_address }}"
kolla_external_vip_address: "{{ kolla_internal_vip_address }}"
kolla_external_fqdn: "{{ kolla_external_vip_address }}"
kolla_base_distro: "centos"
kolla_install_type: "source"
openstack_release: "3.0.1"

# Network Interface
network_interface: "ens160"
#neutron_external_interface: "ens192"
kolla_external_vip_interface: "{{ network_interface }}"
api_interface: "{{ network_interface }}"
storage_interface: "{{ network_interface }}"
cluster_interface: "{{ network_interface }}"
tunnel_interface: "{{ network_interface }}"
neutron_plugin_agent: "openvswitch"


# Private docker registry
#docker_registry: "hub.trystack.cn"
#docker_namespace: "kolla"
#docker_registry_username:
#docker_registry_password:

# Enable services
enable_aodh: "no"
enable_barbican: "no"
enable_ceilometer: "no"
enable_central_logging: "no"
enable_ceph: "no"
enable_ceph_rgw: "no"
enable_cinder: "no"
enable_cinder_backend_iscsi: "no"
enable_cinder_backend_lvm: "no"
enable_cinder_backend_nfs: "no"
enable_cloudkitty: "no"
enable_congress: "no"
enable_destroy_images: "no"
enable_etcd: "no"
enable_gnocchi: "no"
enable_grafana: "no"
enable_heat: "yes"
enable_horizon: "yes"
enable_influxdb: "no"
enable_ironic: "no"
enable_kuryr: "no"
enable_magnum: "no"
enable_manila: "no"
enable_manila_backend_generic: "no"
enable_manila_backend_hnas: "no"
enable_mistral: "no"
enable_mongodb: "no"
enable_murano: "no"
enable_multipathd: "no"
enable_neutron_dvr: "no"
enable_neutron_lbaas: "no"
enable_neutron_fwaas: "no"
enable_neutron_qos: "no"
enable_neutron_agent_ha: "no"
enable_neutron_vpnaas: "no"
enable_octavia: "no"
enable_rally: "no"
enable_sahara: "no"
enable_searchlight: "no"
enable_senlin: "no"
enable_solum: "no"
enable_swift: "no"
enable_telegraf: "no"
enable_tacker: "no"
enable_tempest: "no"
enable_watcher: "no"

# Ceph settings
ceph_enable_cache: "no"
ceph_cache_mode: "writeback"
nova_backend_ceph: "{{ enable_ceph }}"

# Keystone
keystone_token_provider: "uuid"
fernet_token_expiry: 86400

# Glance
glance_backend_file: "yes"
glance_backend_ceph: "no"

# Ceilometer
ceilometer_database_type: "mongodb"
gnocchi_backend_storage: "{{ 'ceph' if enable_ceph|bool else 'file' }}"

# Cinder
cinder_backend_ceph: "{{ enable_ceph }}"
cinder_volume_group: "cinder-volumes"
cinder_backup_driver: "nfs"
cinder_backup_share: ""
cinder_backup_mount_options_nfs: ""

# Horizon
horizon_backend_database: "no"

# Tempest
tempest_image_id:
tempest_flavor_ref_id:
tempest_public_network_id:
tempest_floating_network_name:
tempest_image_alt_id: "{{ tempest_image_id }}"
tempest_flavor_ref_alt_id: "{{ tempest_flavor_ref_id }}"